url: https://cdrc1103.github.io
baseurl: ""

# Site settings
title: Cedric Issel
email: cedric.issel@gmail.com
description: "Lead AI Engineer with 4+ years delivering production AI systems in the cloud for international clients. Proven track record architecting LLM-powered solutions (RAG, validation, custom guardrails) and leading cross-functional, multi-cultural teams (up to 50 developers). Specialized in scaling AI prototypes to production-grade solutions with measurable business impact in highly regulated domains."

# Team names, titles and social links
people:
- name: Cedric Issel
  pic: 1
  position: Lead AI Engineer
  social:
    - title: linkedin
      url: https://linkedin.com/in/cedric-issel
    - title: github
      url: https://github.com/cdrc1103

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://linkedin.com/in/cedric-issel
  - title: github
    url: https://github.com/cdrc1103

# Postal address (add as many lines as necessary)
address:
  - line: Munich, Germany

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Plugins
plugins:
  - jekyll-sitemap
